[pytest]
python_files = test_*.py
python_functions = test_*
python_classes = Test*
addopts = -vv -s -p no:cacheprovider
testpaths = tests
norecursedirs = .venv .git .idea __pycache__

markers =
    smoke: быстрая проверка основных функций
    regression: полная проверка функционала
    slow: длительные тесты